/**:
  ros__parameters:
    wheel_radius: 0.31
    wheel_width: 0.18
    wheel_base: 2.75 # between front wheel center and rear wheel center
    wheel_tread: 1.485 # between left wheel center and right wheel center
    front_overhang: 0.8 # between front wheel center and vehicle front
    rear_overhang: 0.85 # between rear wheel center and vehicle rear
    left_overhang: 0.105 # between left wheel center and vehicle left
    right_overhang: 0.105 # between right wheel center and vehicle right
    vehicle_height: 2.5
    max_steer_angle: 0.55 # [rad]
